apiVersion: v2
name: soketi
description: Just another simple, fast, and resilient open-source WebSockets server.
type: application
version: 0.1.0
appVersion: "1.2.0"
dependencies:
- name: common
  version: 1.0.0
  repository: https://sun-asterisk-research.github.io/helm-charts
- name: redis
  version: 16.13.1
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version: 11.6.12
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
