apiVersion: v2
name: soketi
description: Just another simple, fast, and resilient open-source WebSockets server.
type: application
version: 0.1.0
appVersion: "1.0.1"
dependencies:
- name: common
  version: 1.13.0
  repository: https://charts.bitnami.com/bitnami
- name: redis
  version: 16.8.7
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version: 11.1.24
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
