apiVersion: v2
name: common
description: A Library Helm Chart for grouping common logic
type: library
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: common
  version: 1.16.0
  repository: https://charts.bitnami.com/bitnami
