apiVersion: v2
name: blackbox-monitoring
description: Blackbox monitoring with Prometheus, Alertmanager and Grafana
type: application
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: common
  version: 0.2.0
  repository: https://sun-asterisk-research.github.io/helm-charts
- name: prometheus
  version: 15.5.3
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: prometheus-blackbox-exporter
  version: 5.4.1
  repository: https://prometheus-community.github.io/helm-charts
  alias: blackbox-exporter
- name: grafana
  version: 6.24.0
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
