apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
data:
  config.json: |-
    {{- .Values.config | toPrettyJson | nindent 4 }}
