apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
data:
  config.json: |-
    {{- .Values.config | toPrettyJson | nindent 4 }}
  .env: |-
    {{- if and (empty .Values.config.database.redis) .Values.redis.enabled }}
    SOKETI_DB_REDIS_HOST={{ include "common.subchart.tpl" (dict "context" . "subchart" "redis" "tpl" "common.names.fullname") }}
    SOKETI_DB_REDIS_PORT={{ .Values.redis.master.service.ports.redis }}
    SOKETI_DB_REDIS_PASSWORD={{ .Values.redis.auth.password }}
    {{- end }}
    {{- if and (empty .Values.config.database.postgres) .Values.postgresql.enabled }}
    SOKETI_DB_POSTGRES_HOST={{ include "common.subchart.tpl" (dict "context" . "subchart" "postgresql" "tpl" "common.names.fullname") }}
    SOKETI_DB_POSTGRES_PORT={{ .Values.postgresql.primary.service.ports.postgresql }}
    SOKETI_DB_POSTGRES_DATABASE={{ .Values.postgresql.auth.database }}
    SOKETI_DB_POSTGRES_USERNAME={{ .Values.postgresql.auth.username }}
    SOKETI_DB_POSTGRES_PASSWORD={{ .Values.postgresql.auth.password }}
    {{- end }}
