apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 6001
    protocol: TCP
    name: ws
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    {{- if .Values.networkWatcher.enabled }}
    ws.soketi.app/accepts-new-connections: "yes"
    {{- end }}
