{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-grafana-datasources
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{ $.Values.grafana.sidecar.datasources.label }}: {{ $.Values.grafana.sidecar.datasources.labelValue }}
type: Opaque
stringData:
  datasources.yml: |
    {{- tpl (.Files.Get "grafana/datasources.yml.gotmpl") . | nindent 4 }}
{{- end -}}
