name: GitHub CI

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  release-charts:
    name: Release Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add dependency chart repositories
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add sunasteriskrnd https://sun-asterisk-research.github.io/helm-charts
          helm repo update

      - name: Release Charts
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
